<a href="https://colab.research.google.com/github/farmanali11/core-ai-learning/blob/main/supervised_word_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot

from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [2]:
reviews = [
        'nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement'
]

sentiments = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing resturant",30)


[20, 5]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[15, 7], [20, 29], [27, 1], [8, 4, 11], [8, 10, 20], [1, 7], [18, 10, 11], [10, 3], [10, 19], [21, 23]]


In [5]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[15  7  0  0]
 [20 29  0  0]
 [27  1  0  0]
 [ 8  4 11  0]
 [ 8 10 20  0]
 [ 1  7  0  0]
 [18 10 11  0]
 [10  3  0  0]
 [10 19  0  0]
 [21 23  0  0]]


In [6]:
embedded_vector =5
model = Sequential()
model.add(Embedding(vocab_size,embedded_vector,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [8]:
X = padded_reviews
y = sentiments


In [9]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.fit(X, y, epochs=50, verbose=0)

In [11]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step - accuracy: 1.0000 - loss: 0.6477


1.0

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [13]:

weights[13]

array([-0.00325901,  0.00246876,  0.01271827, -0.0078984 ,  0.02812526],
      dtype=float32)