In [1]:
import numpy as np

x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y=np.array([0,1,1,1])
x


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [2]:
y


array([0, 1, 1, 1])

In [3]:
w=np.array([1,1])


In [4]:
b=-0.5


In [5]:
def activation(z):
    if z >= 0:
        return 1
    else:
        return 0


In [6]:
pred = []

for a in x:
  y_hat =np.dot(a,w) + b

  pred.append(activation(y_hat))


In [7]:
pred


[0, 1, 1, 1]

In [8]:
import math


In [9]:
epochs = 100
alpha = 0.2


In [ ]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()

print("Initial Weights:")

print("w0 =",w0,"w1 = ",w1,"w2 = ",w2)


Initial Weights:
w0 = 0.1499681718612691 w1 =  0.821234733572827 w2 =  0.5127749330313648


In [11]:
del_w0 = 1
del_w1 = 1
del_w2 = 1


In [12]:
train_data_temp = [
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1],
]

train_data = np.asarray(train_data_temp)

op = np.array([0,1,1,1,1,1,1,1,1])


In [13]:
train_data


array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [ ]:
op


array([0, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
bias =0
for i in range(epochs):
    j=0
    for x in train_data:
        y_hat =   w0*x[0]+w1*x[1]+w2*x[2]+bias

        if (y_hat >=0):
            act =1
        else:
            act =0

        err = op[j] - act 

        del_w0 = alpha * x[0] * err
        del_w1 = alpha * x[1] * err
        del_w2 = alpha * x[2] * err

        w0 = w0+del_w0
        w1 = w1+del_w1
        w2 = w2+del_w2

        j = j+1

print("epochs",i+1,"error",err)
print(del_w0,del_w1,del_w2)

print("Final Wight is \n")
print("w0",w0)
print("w1",w1)
print("w2",w2)


epochs 100 error 0
0.0 0.0 0.0
Final Wight is 

w0 0.1499681718612691
w1 0.821234733572827
w2 0.5127749330313648
