In [36]:
import numpy as np

In [37]:
a = np.array([1,2,3,4,5,6])

print(a)

[1 2 3 4 5 6]


In [ ]:
a.ndimn

1

In [39]:
a.shape

(6,)

In [40]:
np.zeros(2)
np.ones(2)

array([1., 1.])

In [41]:
np.arange(4)

array([0, 1, 2, 3])

In [42]:
arr = np.sort([2,1,5,3,7,4,6,8])

In [43]:
np.sort(arr)

a = np.array([1,2,3,4])
b = np.array([5,6,7,8,9])

np.concatenate((a,b))


array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

array_example.shape

(3, 2, 4)

In [44]:
a = np.arange(6)

print(a)

b = a.reshape(3,2)

np.reshape(a,shape =(1,6))


[0 1 2 3 4 5]


array([[0, 1, 2, 3, 4, 5]])

In [45]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [46]:
row_vector = a[np.newaxis,:]

row_vector.shape

(1, 6)

In [47]:
b = np.expand_dims(a,axis = 1)

b.shape

(6, 1)

In [48]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a<5])

five_up = (a>=5)
print(a[five_up])


divide_by_two = (a%2 ==0)

print(a[divide_by_two])

[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


In [49]:
c = a[(a>2)& (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


### Basic array operations

In [50]:
data = np.array([1,2])
ones = np.ones(2,dtype=int)
data+ones

array([2, 3])

In [51]:
data - ones

array([0, 1])

In [52]:
data*data

array([1, 4])

In [53]:
data/data

array([1., 1.])

In [54]:
a = np.array([1,2,3,4])
a.sum()

np.int64(10)

In [55]:
b = np.array([[1,2,3],[4,5,6]])

b.sum(axis=0)

array([5, 7, 9])

In [56]:
c = np.array([[1,2,3],[4,5,6]])
c.sum(axis=1)

array([ 6, 15])

### Broadcasting

In [57]:
data = np.array([1.0,2.0])

data * 1.6

array([1.6, 3.2])

### More useful array operations

In [58]:
data = np.array([1,2,3])
data.max()


np.int64(3)

In [59]:
data.min()

np.int64(1)

In [60]:
data.sum()

np.int64(6)

In [61]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

a.sum()

np.float64(4.8595784)

In [62]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [63]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
data[0,1]

np.int64(2)

### Creating matrices

In [65]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
data[0,1]

np.int64(2)

In [67]:
data.max()

np.int64(6)

In [68]:
data.min()

np.int64(1)

In [69]:
data = np.array([[1,2],[4,5]])
ones = np.array([[1,1],[1,1]])
data + ones

array([[2, 3],
       [5, 6]])

In [70]:
data = np.array([[1,2],[3,4],[5,6]])

ones = np.array([[1,1]])
data + ones

array([[2, 3],
       [4, 5],
       [6, 7]])

In [71]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### Generating random numbers

In [72]:
rng = np.random.default_rng()
rng.random((3,2))

array([[0.09374047, 0.38459086],
       [0.54663931, 0.41614021],
       [0.05218012, 0.86427248]])

In [73]:
  rng.integers(5,size=(4,5))

array([[4, 2, 0, 3, 2],
       [1, 0, 4, 0, 4],
       [4, 1, 4, 3, 1],
       [1, 3, 3, 2, 2]])

### How to get unique items and counts

In [74]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_value = np.unique(a)
print(unique_value)

[11 12 13 14 15 16 17 18 19 20]


In [80]:
unique_value,indices_list = np.unique(a,return_index=True)

print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [82]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_value = np.unique_values(a_2d)
print(unique_value)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [84]:
unique_rows = np.unique_values(a_2d,axis=0)
print(unique_rows)

TypeError: unique_values() got an unexpected keyword argument 'axis'

In [85]:
unique_rows,indices,occurence_count = np.unique(a_2d,axis=0,return_counts=True,return_index=True)

print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [86]:
print(indices)

[0 1 2]


In [87]:
print(occurence_count)

[2 1 1]


### Transposing and reshaping a matrix

In [88]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
arr = np.arange(6).reshape(2,3)
print(arr)

[[0 1 2]
 [3 4 5]]


In [93]:
arr.transpose()


array([[0, 3],
       [1, 4],
       [2, 5]])

In [94]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

### How to reverse an array

In [95]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
rvrs= np.flip(arr)
print(rvrs)

[8 7 6 5 4 3 2 1]


In [99]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

revese = np.flip(arr_2d)
print(revese)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [102]:
revv_arr = np.flip(arr_2d,axis=0)
print(revv_arr)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


### Reshaping and flattening multidimensional arrays

In [103]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
a1 = x.flatten()
a1[0] =99

print(x)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [107]:
a2 = x.ravel()
a2[0] = 90

print(x)
print(a2)

[[90  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[90  2  3  4  5  6  7  8  9 10 11 12]


### How to access the docstring for more information

In [108]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [109]:
max?

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method

In [110]:
a = np.array([1, 2, 3, 4, 5, 6])

I[n] = a?

Type:            ndarray
String form:     [1 2 3 4 5 6]
Length:          6
File:            c:\users\farma\miniconda3\envs\ml\lib\site-packages\numpy\__init__.py
Docstring:      
ndarray(shape, dtype=None, buffer=None, offset=0, strides=None, order=None)
--

ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes 

In [111]:
a??

Type:            ndarray
String form:     [1 2 3 4 5 6]
Length:          6
File:            c:\users\farma\miniconda3\envs\ml\lib\site-packages\numpy\__init__.py
Docstring:      
ndarray(shape, dtype=None, buffer=None, offset=0, strides=None, order=None)
--

ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes 

### Working with mathematical formulas

### How to save and load NumPy objects