In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)

In [3]:
a.shape

(2, 3)

In [4]:
a.ndim

2

In [5]:
a.dtype

dtype('float32')

In [6]:
a.itemsize

4

In [7]:
a.nbytes

24

In [8]:
np.array([1,2,3]).dtype

dtype('int64')

In [9]:
np.array([1,0,2,3]).dtype

dtype('int64')

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [14]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [17]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])